### ISSUE TITLE
Create a repository for AskScript Playground

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#183]
Blocked on: [Use Monaco Editor in AskScript Playground](https://github.com/xFAANG/askql/issues/182)

**Comment by czerwinskilukasz1** [comment]
The AskScript Playground will live here https://github.com/xFAANG/askql-playground

**Comment by czerwinskilukasz1** [comment]
Done

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 how are you planning on assuring the quality of this code when you commit it into a separate repo. We already have measure in this one such us prettier, linter and tests to assure quality. I'm also concerned that by adding another repo it will be more difficult for us to manage the entire project and its deployments. I'd prefer to continue going in the direction of monorepo here.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer Playground frontend is connecting AskQL backend and askql.org frontend. Both of them are separate repos, also AskQL backend repo is, well, backend, so I thought keeping Playground frontend separately would prevent introducing too much complexity in one repo.
What are your thoughts?

**Comment by mhagmajer** [comment]
AskQL.org is a website where we would like to use the playground, yes. That does not mean that the code for playground frontend should go into that repo or its own repo. In my opinion it should go into the main project repo because of the arguments I listed in the previous comment.

I'm not sure what you are referring to as "AskQL backend repo". We have this one monorepo with all the quality measures in place for all software that is AskQL related.

**Comment by czerwinskilukasz1** [comment]
Ok, thanks, I will add it to the main repo then.
