### ISSUE TITLE
AskScript Playground: Consider adding a window which allows to define own resources in Javascript

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#185]
Rationale:
AskVM works on _resources_ and on a real server it's possible to define own resources.
AskScript Playground is missing this feature, so how about we add a text field where user can define their resources in Javascript?
Note that this is potentially dangerous since the resources would be defined in Javascript and potentially a user could run arbitrary code, so we need a good discussion and a plan.

**Comment by mhagmajer** [comment]
Resources are the way to integrate AskVM with the host environment so that programs that run in AskVM can make use of these. If you want to add custom routines in playground you can do so by defining a function with the `fun` resource. What's the value of allowing the playground users add custom resources? Wouldn't that be allowing them run arbitrary JS code on directly in Node?

**Comment by czerwinskilukasz1** [comment]
>  Wouldn't that be allowing them run arbitrary JS code on directly in Node?

@mhagmajer, it is exactly what I wrote above. 


> Resources are the way to integrate AskVM with the host environment so that programs that run in AskVM can make use of these. If you want to add custom routines in playground you can do so by defining a function with the `fun` resource. What's the value of allowing the playground users add custom resources?

As I wrote in the comment above:
> AskVM works on resources and on a real server it's possible to define own resources. 

The resources on AskVM are defined in Javascript not in AskScript, so your solution wouldn't provide the experience.

**Comment by mhagmajer** [comment]
Thanks for clarifying. I think we should not do this because it would allow people using playground to run JavaScript code against a backend and we cannot guarantee safety this way. As the AskQL matures there will be fewer and fewer reasons to write custom resources anyway - you'll just use the existing ones for most everyday use cases.

**Comment by czerwinskilukasz1** [comment]
Fine, I agree that when the ecosystem matures, people could use ready-to-made resources more and more often.
