### ISSUE TITLE
Custom resources no longer accessible

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#222]
Between Jun 16 and Jun 21 AskVM stopped supporting custom resources.

Steps to reproduce:
Add to `cli.ts` the following snippet:

```
export const customResources: Resources = {
  hi: resource<string, []>({
    resolver: async (): Promise<string> => {
      return "Hi, this is AskQL server! It's " + new Date().toString();
    },
  }),
};
```

and change:
```
const options: Options = {
  resources,
  values,
};
```
to:
```
const options: Options = {
  resources: { ...resources, ...customResources },
  values,
};
```

For commit `2bca44`, Tue Jun 16 14:34:31 2020 +0200 CLI works as follows:
```
🦄 hi
string ask(get('hi'))
"Hi, this is AskQL server! It's Thu Jun 25 2020 15:55:17 GMT+0200 (Central European Summer Time)"
🦄 
```

But for commit `f8793d1` aka `v1.1.0`, Sun Jun 21 00:04:04 2020 +0200 instead of the resource CLI returns:
```
🦄 hi
code ask(get('hi'))
AskCode { name: 'hi', params: undefined }
```

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , was there any breaking change to the resource definition?

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 yes, when you reference `hello` being a resource like this you now get back a function, not the result of calling it. I needed to make this change to fix https://github.com/xFAANG/askql/pull/178. This only concerns referencing resources for value (aka "getting"), not calling them which is our main use case. That's why I wouldn't call it a breaking change. We have often used it for `empty`, `true`, `false` resources which are now parsed to calling underlying resources. So what you are seeing here is the expected behaviour and the previous one was a bug.

**Comment by mhagmajer** [comment]
You need to do `hi()`

**Comment by czerwinskilukasz1** [comment]
Got it, this is the change, thanks.
