### ISSUE TITLE
Implement extend resource create a new object with added property

### ISSUE THREAD

**Issue by czerwinskilukasz1** [xFAANG/askql#257]
While we have a resource for setting a value in an array (`set` resource), I think we don't have such for objects.

It is up to discussion whether a new resource should be created or rather `set` should be extended to work for objects.

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , any thoughts?

**Comment by mhagmajer** [comment]
Because of data mutability we need to support `extend` for objects.

```
let a = { firstName: 'John' }
let b = extend(a, { lastName: 'Smith' }
```

should return `{ firstName: 'John', lastName: 'Smith' }`

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , would `extend` also _change_ a value of an existing key?
E.g.:
```
let a = { firstName: 'John' }
a = extend(a, { firstName: 'Bill' }
```

**Comment by mhagmajer** [comment]
@czerwinskilukasz1 

```
let a = { firstName: 'John' } // object X
a = extend(a, { firstName: 'Bill' } // object Y
```

Object X is going to stay the same no matter what you do. Object Y will be creating by extending object X which will overwrite its only property. Variable `a` is like a pointer. It can change what it points to because it is declared with `let`.  It initially points to object X and then it points to object Y. Object X and object Y are immutable.

**Comment by czerwinskilukasz1** [comment]
Yes, I know. That's why I wrote 'change' in _italics_. Anyways, you answered my question: yes, extend will also work on a key that is already defined. So using extend could be a workaround for updating a value in a map.
Anyway, don't we need a `set` resource for maps?
