### ISSUE TITLE
AskVM not timing out on infinite loops

### ISSUE THREAD

**Issue by DavidSampson** [xFAANG/askql#29]
According to the [FAQ](https://www.notion.so/FAQ-554ab8a775494057a0fdbedf7ad6f2d6), the AskVM should timeout on infinite loops.

However running the following in the AskVM generates a hang (infinite loop) that does not seem to resolve.

```
const f = fun():any {
  call(f)
}
call(f)
```

To replicate:
* `npm install askql`
* `./askql`
* `.editor`
* Enter the above code
* Ctrl+D

**Comment by undomalum** [comment]
Thank you, David, for your contribution! We will definitely look into it. We'll keep you posted :)

**Comment by DavidSampson** [comment]
More generally, how does AskQL and AskVM plan to handle cases like this?

If there's a limit to "steps" (beta reductions if this is a lambda calculus evaluator) or something similar, and the code written in the front end is O(n) where n is, say, the number of entries in a table,  then a working query may suddenly start failing, and the only change is that a new entry was added to the table. That seems like a lot of hassle for the front end developer -- you have to anticipate your query failing for reasons that are outside of your control.

If it's a time limit, then you have the same issue, except now it's even more non-deterministic, since server load will effect whether a query times out. It seems like that would be a testing nightmare.

**Comment by mhagmajer** [comment]
Thanks @DavidSampson for posting this! You have definitely spotted a bug and we're going to send a PR that solves it soon.

Speaking of this issue more broadly, every server indeed has different set of limited resources that it can devote to running a query (regardless of the query language). I agree that in case of AskQL this gets tricker, because more operations are possible - including endless loops, stack overflows, heap overflows - just to name a few. We're going to address it by a) adding more different kinds of limits you can set for the VM b) allowing programs to query the information about their current limits at runtime so that they have an option to check the limits and adapt their behaviour.

These limits will include the number of operations, stack size, time allotted, and heap size. They are deterministic, yet their respective behaviour may vary by the server - especially the time limit which is subject to other workload. We'll make sure that if AskVM returns an error, it will include all details possible on what limit has caused it, why, and what are the recommended steps for the developer. If there are other measures to help with development experience, we'll look into these as well.

Please treat this as introductory input in this important discussion, more will follow. Thanks again, @DavidSampson, for your participation and creating this issue!

**Comment by czerwinskilukasz1** [comment]
@mhagmajer , what's the update on this ticket?

**Comment by mhagmajer** [comment]
Marking this as a release blocker to support running playground safely

**Comment by czerwinskilukasz1** [comment]
@DavidSampson , thank you a million for posting this issue. 
We created a PR which resolves it and would be thrilled if you could comment on our solution: https://github.com/xFAANG/askql/pull/220
